my_blog/app_admin/urls.py
from django.urls import path
from .views import dashboard, user_articles, AddArticle, UpdateArticle, DeleteArticle

urlpatterns = [
    path('', dashboard, name="dashboard"),
    path('my-articles', user_articles, name="my-articles"),
    path('ajouter-article', AddArticle.as_view(), name="ajouter-article"),
    path('update-article/<int:pk>', UpdateArticle.as_view(), name="update-article"),
    path('delete-article/<int:pk>', DeleteArticle.as_view(), name="delete-article"),
]

my_blog/app_auth/urls.py
from django.urls import path
from .views import *

urlpatterns=[

    path('login',login_blog,name='login-blog'),
    path('register',register,name='register'),
    path('logout',logout_blog,name='logout'),



]

my_blog/blog/urls.py
from django.urls import path
from  . import views 


urlpatterns=[
    path("",views.home , name="home"),
]

my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from blog.views import home,detail,search




urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home,name="home"),
    path('article/<int:id_article>',detail,name="detail"),
     path('article/recherche',search,name="search"),
     path('auth/',include("app_auth.urls")),
     path('my-admin/',include("app_admin.urls")),
   
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

my_blog/app_admin/models.py
from django.db import models

# Create your models here.

my_blog/app_auth/models.py
from django.db import models

# Create your models here.

my_blog/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Category(models.Model):
   name=models.CharField(max_length=120)

   def __str__(self):
        return self.name


class Article (models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    title=models.CharField(max_length=50)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    desc=models.TextField()
    image=models.ImageField(null=True,blank=True)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("my-articles")
       
       
   
    

my_blog/app_auth/forms.py
from django import forms

class loginForm(forms.Form):
    username = forms.CharField(label="Nom utilisateur",widget=forms.TextInput(attrs={'class':'form-control'}))
    pwd = forms.CharField(label="Mot de passe",widget=forms.PasswordInput(attrs={'class':'form-control'}))

class RegisterForm(forms.Form):
    username = forms.CharField(label="Nom utilisateur",widget=forms.TextInput(attrs={'class':'form-control'}))
    pwd = forms.CharField(label="Mot de passe",widget=forms.PasswordInput(attrs={'class':'form-control'}))  
    pwd_confirm = forms.CharField(label="Mot de passe de confirmation",widget=forms.PasswordInput(attrs={'class':'form-control'}))  
   

my_blog/blog/forms.py
from django import forms
from .models import Article
 
class ArticleForm(forms.ModelForm):
  class Meta:
    model = Article
    fields = ['title','category','desc', 'image']
    labels = {'title':'Title','category':'Categorie','desc':'Description'}
    widgets={
      'title':forms.TextInput(attrs={'class':'form-control'}),
      'category':forms.Select(attrs={'class':'form-control'}),
      'desc':forms.Textarea(attrs={'class':'form-control','rows':5}),

    }
   
 

my_blog/app_admin/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import UpdateView, CreateView ,DeleteView
from blog.models import Article
from blog.forms import ArticleForm

# Create your views here.
def dashboard(request):
    return render(request, 'db.html')

def user_articles(request):
    if not request.user.is_authenticated:
        return redirect('home')

    list_articles = Article.objects.filter(user=request.user)
    return render(request, 'my-articles.html', {'list_articles': list_articles})

class AddArticle(CreateView):
    model = Article
    form_class = ArticleForm
    template_name = "add-article.html"
    success_url = "my-articles"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class UpdateArticle(UpdateView):
    model = Article
    form_class = ArticleForm
    template_name = 'app_admin/article_form.html'
   

class DeleteArticle(DeleteView):
    model = Article
    success_url = "/my-admin/my-articles"
    

my_blog/app_auth/views.py
from urllib import request
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import *

# Create your views here.
def login_blog(request):
    if request.method == "POST":
        form = loginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            pwd = form.cleaned_data['pwd']
            user = authenticate(username=username,password=pwd)
            if user is not None:
                login(request,user)
              
                return redirect('home')
            else:
                messages.error(request,"Authentification échouée")
                return render(request,'login.html',{'form':form})
        else:
             for field in form.errors:
                 
              form[field].field.widget.attrs['class'] += 'is-invalid'

             return render(request,'login.html',{'form':form})
    else :

        form = loginForm()
        return render(request,'login.html',{'form':form})
    

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            pwd = form.cleaned_data['pwd']
            user = User.objects.create_user(username=username, password=pwd)
            if user is not None:
                return redirect("login-blog")
            else:
                messages.error(request, 'Création compte échouée')
                return render(request, 'register.html', {'form': form})
        else:
            return render(request, 'register.html', {'form': form})
    else:
        form = RegisterForm()
        return render(request, 'register.html', {'form': form})
    

def logout_blog(request):
    logout(request)
    return redirect('login-blog')


       

my_blog/blog/views.py
from django.shortcuts import render
from .models import Article

def home(request):
    list_articles = Article.objects.all()
    context = {"liste_articles": list_articles}
    return render(request, "index.html", context)

def detail(request,id_article):
    article=Article.objects.get(id=id_article)
    category=article.category
    articles_en_relations=Article.objects.filter(category=category)[:5]
    return render(request, "detail.html",{"article":article,"aer":articles_en_relations})

def search(request):
    query=request.GET["article"]
    liste_article=Article.objects.filter(title__icontains=query)
    return render(request,"search.html",{"liste_article":liste_article})

  

my_blog/app_admin/templates/add-article.html
{% extends 'partials/base.html' %}

{%  block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
        <h2 class="text-center">Saisie des articles</h2>
            <form action="" method="POST" enctype="multipart/form-data">
              {% csrf_token %}
               {{form}}
              <button class="btn btn-primary btn-block">Enregistrer</button>
            </form>
           
        </div>
    </div>
</div>

{% endblock  %}

my_blog/app_admin/templates/app_admin/article_form.html
{%  extends 'partials/base.html' %}

{%  block content %}
  
    <div class="container">
      <div class="row">
        <div class="div col-md-12">
           <div class="card mt-2">
             <div class="card-body">
                <form action="" method="POST">
                    {% csrf_token %}
                   {{form}}
                   <button class="btn btn-success btn-block mt-4">Modifier L'article </button>
                 </form>
             </div>
           </div>
        </div>
      </div>
    </div>
  

{% endblock %}

my_blog/app_admin/templates/db.html
{% extends 'partials/base.html' %}

{% block content %}

 <div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2>Tableau de bord </h2>

        </div>

    </div>
 </div>


 {%  endblock %}

my_blog/app_admin/templates/my-articles.html
{% extends 'partials/base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12"><h2>Mes articles</h2></div>
        <div class="col-md-12">
            <a href="{%  url 'ajouter-article' %}" class="btn btn-secondary float-right"><i class="fas fa-plus"></i>Ajouter article</a>
        </div>
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th class="h6">Titre</th>
                                <th class="h6">Description</th>
                                <th class="h6">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for article in list_articles %}
                                <tr>
                                    <td class="h6"><a href="">{{ article }}</a></td>
                                    <td class="h6"><a href="">{{ article.desc }}</a></td>
                                    <td>
                                        <a href="{% url 'update-article' article.pk %}" class="btn btn-info btn-sm"><i class="fa fa-edit"></i></a>
                                        <a href="{% url 'delete-article' article.pk %}" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

         {% if list_articles %}
            
         {% else %}
            <div class="col-md-12">
                <h3>Vous n'avez aucun article</h3>
            </div>
        {% endif %}
    </div>
</div>

{% endblock %}

my_blog/app_admin/templates/partials/_navadmin.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
   
    <div class="container">
        <a class="navbar-brand text-white">TDB</a>

        <button class="navbar-toggler text-white" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarButtonsExample" aria-controls="navbarButtonsExample" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fas fa-bars"></i>
        </button>

       
        <div class="collapse navbar-collapse" id="navbarButtonsExample">
          
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home' %}">Accueil</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'my-articles' %}">Mes articles</a>
                </li>
            </ul>
           
            <ul class="navbar-nav ml-auto nav-flex-icons">
                  {%  if user.is_authenticated %}
                <li class="nav-item">
                     <span class="nav-link">{{user.username}}</span>
                </li>
                    {%  endif %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-user text-white"></i>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            
                            {%  if user.is_authenticated %}
                          <a class="dropdown-item" href="#">Déconnexion</a>
                            {% endif  %}
                             
                        </div>
                      </li>
            </ul>
            
        </div>
    </div>
</nav>

my_blog/app_admin/templates/partials/base.html
<!DOCTYPE html>
  {%  load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%  block title%} Tableau de bord {% endblock %}</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <!-- Google Fonts Roboto -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Material Design Bootstrap -->
    <link rel="stylesheet" href="{%  static 'css/mdb.min.css' %}">
    
</head>
<body>
         {% include 'partials/_navadmin.html' %}

            {% block content %}
            {% endblock  %}

           
      <!-- jQuery -->
      <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
      <!-- Bootstrap tooltips -->
      <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
      <!-- Bootstrap core JavaScript -->
      <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
      <!-- MDB core JavaScript -->
      <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
    
</body>
</html>

my_blog/app_auth/templates/login.html
{%  extends 'base.html' %}

{% block title  %} Connexion au blog {% endblock %}

{% block content %}


  <div class="container">
    <div class="col-md-12 mt-5">
           {% if messages %}
            {% for message in messages %}
            <div class="alert alert-danger text-center"><strong>{{message}}</strong></div>
            {% endfor %}
           {% endif %}
        <form action="" method="POST" novalidate> {%  csrf_token %}
            <div class="card">
                <div class="card-header text-center"><i class="fas fa-user"></i>Connexion au blog </div>
                 <div class="card-body">
                    <label for="id_username">Nom utilisateur</label>
                     {%  if form.username.errors %}
                     {%  for error in form.username.errors %}
                      <div class="div-error-{{form.username.name}}"><small class="text-danger">{{error}}</small></div>
                     {% endfor %}
                      {% endif %}
                     {{form.username}}
                     <label for="id_pwd">Mot de passe</label>
                       {% if form.pwd.errors %}
                       {% for error in form.pwd.errors %}
                       <div  class="div-error-{{form.pwd.name}}"><small class="text-danger">{{error}}</small></div>
                        {% endfor  %}
                        {%  endif %}
                        {{form.pwd}}
                 </div>
                 <div class="card-footer">
                    <button class="btn btn-primary btn-block">Se connecter</button>
                    <p class="mt-2">Vous n'avez pas de compte ?<a href="{% url 'register' %}">Créer le compte</a></p>
                </div>
               
            </div>
        </form>   
    </div>
  </div>


{% endblock %}

{% block scripts %}
 <script>
  $(document).ready(function(){
       $('input').keyup(function(){
         let textSaisi = $(this).val();


        let attrName = $(this).attr('name');
        let validatorElement = ".div-error-"+attrName;

         if(textSaisi === ""){
            if(!$(this).hasClass('is-invalid')){
                $(this).addClass('is-invalid');

                $(validatorElement).show();

            }

         } else {
            $(this).removeClass('is-invalid');
            $(validatorElement).hide()

         }

      })
  })
 </script>

{%  endblock %}

my_blog/app_auth/templates/register.html
{%  extends 'base.html' %}

{% block title  %} Création du compte au blog {% endblock %}

{% block content %}


  <div class="container">
    <div class="col-md-12 mt-5">
           {% if messages %}
            {% for message in messages %}
            <div class="alert alert-danger text-center"><strong>{{message}}</strong></div>
            {% endfor %}
           {% endif %}
        <form action="" method="POST" novalidate> {%  csrf_token %}
            <div class="card">
                <div class="card-header text-center"><i class="fas fa-user-lock"></i>Création de compte </div>
                 <div class="card-body">
                   {{form}}
                 </div>
                 <div class="card-footer">
                    <button class="btn btn-primary btn-block">Créer le compte</button>
                </div>
            </div>
        </form>   
    </div>
  </div>


{% endblock %}

{% block scripts %}


{%  endblock %}

my_blog/blog/templates/_footer.html
<footer class="bg-primary text-white text-center text-lg-start">
    <!-- Grid container -->
    <div class="container p-4">
      <!--Grid row-->
      <div class="row">
        <!--Grid column-->
        <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
          <h5 class="text-uppercase">Footer Content</h5>
  
          <p>
            
          </p>
        </div>
        <!--Grid column-->
  
        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">Links</h5>
  
          <ul class="list-unstyled mb-0">
            <li>
              <a href="#!" class="text-white">Link 1</a>
            </li>
            <li>
              <a href="#!" class="text-white">Link 2</a>
            </li>
            <li>
              <a href="#!" class="text-white">Link 3</a>
            </li>
            <li>
              <a href="#!" class="text-white">Link 4</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->
  
        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase mb-0">Links</h5>
  
          <ul class="list-unstyled">
            <li>
              <a href="#!" class="text-white">Link 1</a>
            </li>
            <li>
              <a href="#!" class="text-white">Link 2</a>
            </li>
            <li>
              <a href="#!" class="text-white">Link 3</a>
            </li>
            <li>
              <a href="#!" class="text-white">Link 4</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->
      </div>
      <!--Grid row-->
    </div>
    <!-- Grid container -->

    <section class="">
        <!-- Footer -->
        
          <!-- Grid container -->
          <div class="container p-4 pb-0">
            <!-- Section: CTA -->
            <section class="">
              <p class="d-flex justify-content-center align-items-center">
                <span class="me-3">Register for free</span>
                <button data-mdb-ripple-init type="button" class="btn btn-outline-light btn-rounded" style="background-color: #dd4b39;" >
                  Sign up!
                </button>
              </p>
            </section>
            <!-- Section: CTA -->
          </div>
          <!-- Grid container -->
    
      </section>
  
    

        <!-- Grid container -->
        <div class="container p-4 pb-0">
          <!-- Section: Social media -->
          <section class="mb-4">
            <!-- Facebook -->
            <a
            data-mdb-ripple-init
              class="btn text-white btn-floating m-1"
              style="background-color: #3b5998;"
              href="#!"
              role="button"
              ><i class="fab fa-facebook-f"></i
            ></a>
      
            <!-- Twitter -->
            <a
              data-mdb-ripple-init
              class="btn text-white btn-floating m-1"
              style="background-color: #55acee;"
              href="#!"
              role="button"
              ><i class="fab fa-twitter"></i
            ></a>
      
            <!-- Google -->
            <a
              data-mdb-ripple-init
              class="btn text-white btn-floating m-1"
              style="background-color: #dd4b39;"
              href="#!"
              role="button"
              ><i class="fab fa-google"></i
            ></a>
      
            <!-- Instagram -->
            <a
              data-mdb-ripple-init
              class="btn text-white btn-floating m-1"
              style="background-color: #ac2bac;"
              href="#!"
              role="button"
              ><i class="fab fa-instagram"></i
            ></a>
      
            <!-- Linkedin -->
            <a
              data-mdb-ripple-init
              class="btn text-white btn-floating m-1"
              style="background-color: #0082ca;"
              href="#!"
              role="button"
              ><i class="fab fa-linkedin-in"></i
            ></a>
            <!-- Github -->
            <a
              data-mdb-ripple-init
              class="btn text-white btn-floating m-1"
              style="background-color: #333333;"
              href="#!"
              role="button"
              ><i class="fab fa-github"></i
            ></a>
          </section>
          <!-- Section: Social media -->
        </div>
        <!-- Grid container -->
      
        <!-- Copyright -->
        <!-- Copyright -->
     <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        © 2020 Copyright:
        <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
      </div>
      <!-- Copyright -->
        
        <!-- Copyright -->
      
  </footer>

my_blog/blog/templates/_nav.html
<nav class="navbar navbar-expand-lg navbar-ligth">
    <a class="navbar-brand" href="#">My blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Admin 
          <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Contact</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Mon compte
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        
      </ul>
        {% if user.is_authenticated %} 
        <a  href ="{% url 'logout' %}" class="btn btn-info">Déconnexion</a>
        {% else  %} 
        <a  href ="{% url 'login-blog' %}" class="btn btn-info">Connexion</a>
        {% endif %}
       
      <form class="form-inline" action="{% url 'search' %}">
        <div class="md-form my-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Recherche" aria-label="Search" name="article">
      </div>
      </form>
    </div>
  </nav>

my_blog/blog/templates/base.html
<!DOCTYPE html>
  {% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%  block title %}My blog {% endblock %}</title>
     <!-- MDB icon -->
     <link rel="icon" href="img/mdb-favicon.ico" type="image/x-icon">
     <!-- Font Awesome -->
     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
     <!-- Google Fonts Roboto -->
     <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
     <!-- Bootstrap core CSS -->
     <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
     <!-- Material Design Bootstrap -->
     <link rel="stylesheet" href="{%  static 'css/mdb.min.css' %}">
     <!-- Your custom styles (optional) -->
     <link rel="stylesheet" href="{ %  static 'css/style.css' %}">
</head>
<body>
       {% include "_nav.html" %}

       {%  block content %}
       {% endblock %}

       {% include '_footer.html' %}

      <!-- jQuery -->
      <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
      <!-- Bootstrap tooltips -->
      <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
      <!-- Bootstrap core JavaScript -->
      <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
      <!-- MDB core JavaScript -->
      <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
        
       {% block script %}
       {%  endblock %}

    
</body>
</html>

my_blog/blog/templates/blog/article_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

 <div class="container mt-5">
    <div class="row">
        <div class="col-md-12">
            <form action="" method="POST">
                {% csrf_token %}
                <p>Voulez-vous supprimer cet article ? ({{object}})</p>
                <input type="submit" value="Supprimer" class="btn btn-danger">
                 <a href="" class="btn btn-secondary">Non</a>
            </form>
        </div>
    </div>
 </div>

{% endblock %}

my_blog/blog/templates/brouillon.html
{%  include '_nav.html' %}
<h1 class=" text-center mt-2">Detail article</h1>
<img src="{{article.image.url}}"  alt="">
<h2>{{article.title}}</h2>
<p>{{article.desc}}</p>


   

my_blog/blog/templates/detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h1 class="text-center mt-2">Detail article</h1>
            <img src="{{ article.image.url }}" alt="" style="max-width:600px;">
            <h2>{{ article.title }}</h2>
            <p>{{ article.desc }}</p>
        </div>
        <div class="col-md-4">
            <h3 class="mt-2">Les articles en relations</h3>
            <div class="row">
                {% for art in aer %}
                {% if art.id != article.id %}
                <div class="col-md-7 mb-1">
                    {% if art.image != "http://default" %}
                        <img src="{{ art.image.url }}" alt="" style="max-width: 180px;">
                    {% else %}
                        <img class="card-img-top" src="https://via.placeholder.com/400x300"  alt="{{ art.title }}" style="max-width: 100%; height: 200px;">
                    {% endif %}
                </div>
              
                <div class="col-5">
                    <strong>{{ art.title }}</strong> <br>
                    {{ art.desc|truncatewords:7 }}
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

my_blog/blog/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
   
    <h1 class="text-center mt-3">Bienvenue sur notre blog</h1>
    <div class="container">
        <div class="row">
            {% for article in liste_articles %}
                <div class="card col-12 col-md-6 col-lg-3 col-xl-3">
                    <!-- Card image -->
                    <a href="{% url 'detail' article.id %}">
                        {% if not article.image %}
                            <img class="card-img-top" src="{% static 'img/logo.png' %}" alt="Card image cap" style="height: 250px;">
                        {% else %}
                            <img class="card-img-top" src="{{ article.image.url }}" alt="Card image cap" style="height: 250px;">
                        {% endif %}
                    </a>
                    <!-- Card content -->
                    <div class="card-body" style="height: 240px;">
                        <!-- Title -->
                        <h4 class="card-title"><a href="{% url 'detail' article.id %}">{{ article.title }}</a></h4>
                        <!-- Text -->
                        <p class="card-text">{{ article.desc|truncatewords:8 }}</p>
                        <p class="card-text"> Publié il y a {{ article.created_at|timesince }}</p>
                        <!-- Button -->
                        <a href="{% url 'detail' article.id %}" class="btn btn-primary">Lire la suite</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

    

     

  

my_blog/blog/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
 <div class="container">
 <h2>Liste de recherche</h2>
    <div class="row">
    {% for article in liste_article %}
    
    <div class="card col-12 col-md-6 col-lg-3 col-xl-3">
              

        <!-- Card image -->
         
          {% if article.image == "http://default" %}

          
            <a href="{% url 'detail' article.id %}">

         <img class="card-img-top" src="{%  static 'img/logo.png' %}" alt="Card image cap" style="height: 250px;">
          </a>
          {%  else %}
       
        <a href="{% url 'detail' article.id %}">

        <img class="card-img-top" src="{{article.image.url}}" alt="Card image cap" style="height: 250px;">
       </a>
         {% endif %}

        <!-- Card content -->
        <div class="card-body" style="height: 240px;">

            <!-- Title -->
            <h4 class="card-title"><a href="{% url 'detail' article.id %}">{{article.title}}</a></h4>
            <!-- Text -->
            <p class="card-text">{{article.desc|truncatewords:8}}</p>
            <p class="card-text"> Publié il ya {{article.created_at|timesince}}</p>
            <!-- Button -->
            <a href="{% url 'detail' article.id %}" class="btn btn-primary">Lire la suite</a>

        </div>

    </div>
    <!-- Card -->

       {% endfor %}  

    </div>
 </div>
{% endblock %}